
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Compilador;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int CONT = 39;
  public static final int PARCER = 21;
  public static final int DOSPUNTOS = 19;
  public static final int CHARACD = 56;
  public static final int WRTE = 41;
  public static final int MULT = 8;
  public static final int CHAR = 31;
  public static final int SWT = 44;
  public static final int MENORQ = 12;
  public static final int GBAJO = 27;
  public static final int STRINGD = 59;
  public static final int ENTD = 55;
  public static final int CASE = 45;
  public static final int DOUBLE = 30;
  public static final int MENORI = 13;
  public static final int INT = 29;
  public static final int FOR = 46;
  public static final int LLCER = 23;
  public static final int NOT = 26;
  public static final int AND = 24;
  public static final int IGUAL = 10;
  public static final int DECD = 54;
  public static final int RTRN = 38;
  public static final int LETRA = 3;
  public static final int OR = 25;
  public static final int COMS = 28;
  public static final int BOOL = 32;
  public static final int PARAB = 20;
  public static final int DIV = 6;
  public static final int IF = 43;
  public static final int MAIN = 35;
  public static final int ID = 58;
  public static final int PYCOMA = 18;
  public static final int EOF = 0;
  public static final int LLAB = 22;
  public static final int ASIG = 9;
  public static final int TRUE = 50;
  public static final int NEW = 49;
  public static final int error = 1;
  public static final int DESIG = 11;
  public static final int COMA = 17;
  public static final int DIG = 2;
  public static final int CNSL = 40;
  public static final int BOOLEAD = 57;
  public static final int VOID = 34;
  public static final int WhiteSpace = 4;
  public static final int ELSE = 42;
  public static final int PUNTO = 16;
  public static final int MAYORQ = 14;
  public static final int MEN = 7;
  public static final int WHILE = 47;
  public static final int BRK = 37;
  public static final int MAYORI = 15;
  public static final int COMENTS = 53;
  public static final int STRING = 33;
  public static final int DEF = 36;
  public static final int FALSE = 51;
  public static final int COMENTM = 52;
  public static final int DO = 48;
  public static final int MAS = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DIG",
  "LETRA",
  "WhiteSpace",
  "MAS",
  "DIV",
  "MEN",
  "MULT",
  "ASIG",
  "IGUAL",
  "DESIG",
  "MENORQ",
  "MENORI",
  "MAYORQ",
  "MAYORI",
  "PUNTO",
  "COMA",
  "PYCOMA",
  "DOSPUNTOS",
  "PARAB",
  "PARCER",
  "LLAB",
  "LLCER",
  "AND",
  "OR",
  "NOT",
  "GBAJO",
  "COMS",
  "INT",
  "DOUBLE",
  "CHAR",
  "BOOL",
  "STRING",
  "VOID",
  "MAIN",
  "DEF",
  "BRK",
  "RTRN",
  "CONT",
  "CNSL",
  "WRTE",
  "ELSE",
  "IF",
  "SWT",
  "CASE",
  "FOR",
  "WHILE",
  "DO",
  "NEW",
  "TRUE",
  "FALSE",
  "COMENTM",
  "COMENTS",
  "DECD",
  "ENTD",
  "CHARACD",
  "BOOLEAD",
  "ID",
  "STRINGD"
  };
}

